apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # Corrected image path pointing to your Docker Hub repository
        image: abhaydocker732/codtech-frontend:v1
        # Changed to 'Always' to ensure the image is pulled from Docker Hub
        imagePullPolicy: Always
        ports:
        - containerPort: 80
