apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # NodePort makes the service accessible from outside the Kubernetes cluster
  type: NodePort
